const express = require("express")
const router = express.Router()
const geolocationPosts = require('./geolocationPosts')
const latestPosts = require('./latestPosts')
const oldestPosts = require('./oldestPosts')
router.get("/latest", latestPosts)
router.get("/oldest", oldestPosts)
router.get("/:lat/:lng/:radius", geolocationPosts)
const app = express()
const cors = require("cors")
app.use(cors({origin: true}))
app.use(router)
module.exports = app