const express = require("express")
const checkAuth = require("../checkAuth")
const router = express.Router()
const settingsUser = require('./settingsUser')
router.get("/settings", checkAuth, settingsUser)
const app = express()
const cors = require("cors")
app.use(cors({origin: true}))
app.use(checkAuth)
app.use(router)
module.exports = app