const express = require("express")
const checkAuth = require("../checkAuth")
const router = express.Router()
const donate = require("./donate")
router.put("/:id", checkAuth, donate)
router.delete("/:id", checkAuth, donate)
const app = express()
const cors = require("cors")
app.use(cors({origin: true}))
app.use(router)
module.exports = app