const express = require("express")
const checkAuth = require("../checkAuth")
const router = express.Router()
const createPost = require("./createPost")
const contactPost = require("./contactPost")
const deletePost = require("./deletePost")
const latestPost = require("./latestPost")
router.post("/create", createPost)
router.get("/:id/contact", contactPost)
router.delete("/:id/delete", deletePost)
router.get("/latest", latestPost)
const app = express()
const cors = require("cors")
app.use(cors)
app.use(checkAuth)
app.use(router)
module.exports = app