# This is a basic workflow to help you get started with Actions

name: Functions CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, functions ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Use Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # Install dependencies
    - run: npm ci
      working-directory: functions
    
    # Write down secret mapbox token
    - run: echo "module.exports = \"$MAPBOX_TOKEN\"" > ./mapboxToken.js
      working-directory: functions
      env:
        MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
  
    # Write down reCAPTCHA secret
    - run: echo "module.exports = \"$RECAPTCHA_SECRET\"" > ./recaptchaSecret.js
      working-directory: functions
      env:
        RECAPTCHA_SECRET: ${{ secrets.RECAPTCHA_SECRET }}
    
    # Deploy functions
    - name: Deploy to Firebase
      uses: BIGG-Kaymo/deploy-firebase-functions@v1.0.1
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
